#!/usr/bin/env python3
"""
Script to build bundled-sets.js from all JSON files in the bundled/ directory.
This generates a JavaScript file that can be directly included in the HTML.
"""

import json
import sys
from pathlib import Path
from typing import List, Dict, Any

# Fix Windows console encoding
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

BUNDLED_DIR = Path("bundled")
OUTPUT_FILE = Path("bundled-sets.js")


def load_bundled_sets() -> List[Dict[str, Any]]:
    """Load all bundled sets from the bundled directory without validation."""
    if not BUNDLED_DIR.exists():
        print(f"❌ Bundled directory '{BUNDLED_DIR}' does not exist")
        return []
    
    json_files = list(BUNDLED_DIR.glob("*.json"))
    # Exclude index.json from the list
    json_files = [f for f in json_files if f.name != "index.json"]
    
    if not json_files:
        print(f"⚠️  No JSON files found in '{BUNDLED_DIR}' directory")
        return []
    
    print(f"📁 Found {len(json_files)} JSON file(s) in '{BUNDLED_DIR}' directory\n")
    
    sets = []
    
    for json_file in sorted(json_files):
        print(f"📄 Processing: {json_file.name}")
        
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # Store the original filename
            if isinstance(data, dict):
                data['bundledFileName'] = json_file.name
                data['bundled'] = True
                sets.append(data)
                card_count = len(data.get("cards", [])) if isinstance(data.get("cards"), list) else 0
                name = data.get("name", "Unknown")
                print(f"   ✅ Loaded: '{name}' ({card_count} cards)")
            else:
                print(f"   ⚠️  Skipping: File is not a JSON object")
        
        except json.JSONDecodeError as e:
            print(f"   ❌ Invalid JSON: {e}")
            print(f"   ⚠️  Skipping this file")
        except Exception as e:
            print(f"   ❌ Error reading file: {e}")
            print(f"   ⚠️  Skipping this file")
        
        print()
    
    return sets


def generate_js_file(sets: List[Dict[str, Any]]) -> None:
    """Generate the bundled-sets.js file."""
    import hashlib
    from datetime import datetime
    
    if not sets:
        print("⚠️  No sets to generate")
        # Generate empty file
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("// Auto-generated by build_bundled_sets.py\n")
            f.write("// No bundled sets found\n")
            f.write("const bundledSetsData = [];\n")
        print(f"✅ Generated empty '{OUTPUT_FILE}'")
        return
    
    try:
        # Create content hash for cache-busting
        content_str = json.dumps(sets, sort_keys=True, ensure_ascii=False)
        content_hash = hashlib.md5(content_str.encode('utf-8')).hexdigest()[:8]
        build_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("// Auto-generated by build_bundled_sets.py\n")
            f.write(f"// Build time: {build_time}\n")
            f.write(f"// Content hash: {content_hash}\n")
            f.write("// Do not edit this file manually - run build_bundled_sets.py to regenerate\n\n")
            f.write("const bundledSetsData = ")
            json.dump(sets, f, indent=2, ensure_ascii=False)
            f.write(";\n")
        
        print(f"✅ Generated '{OUTPUT_FILE}' with {len(sets)} set(s)")
        print(f"   Content hash: {content_hash}")
        print(f"   ⚠️  Update HTML cache-busting: bundled-sets.js?v={content_hash}")
    except Exception as e:
        print(f"❌ Failed to generate '{OUTPUT_FILE}': {e}")
        sys.exit(1)


def main():
    """Main function."""
    print("=" * 60)
    print("🔨 Building Bundled Sets JavaScript File")
    print("=" * 60)
    print()
    
    sets = load_bundled_sets()
    
    print("=" * 60)
    print("📊 Summary")
    print("=" * 60)
    print(f"Total sets loaded: {len(sets)}")
    
    if sets:
        print("\nSets included:")
        for s in sets:
            name = s.get("name", "Unknown")
            card_count = len(s.get("cards", [])) if isinstance(s.get("cards"), list) else 0
            filename = s.get("bundledFileName", "Unknown")
            print(f"  - {filename}: {name} ({card_count} cards)")
    
    print()
    print("=" * 60)
    generate_js_file(sets)
    print("=" * 60)
    print("\n✅ Build complete!")


if __name__ == "__main__":
    main()

